version: '3.7'

services:

  api:
    build:
      context: ./
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: runa_db
      POSTGRES_USER: runa_user
      POSTGRES_PASSWORD: password
    expose:
      - 5432